### ISSUE TITLE
Scout

### ISSUE THREAD

**Issue by Sn0x92** [stefan2200/TWB#1]
Hey, what do I have to set exactly so that the bot other players spy?
He never says enough Spy.

Only BB are attacked.

**Comment by stefan2200** [comment]
Hi,

The config file contains a list for each village called: "additional_farms". You can enter the village ID's of nearby player owned villages (or event villages etc..), I assume the ID's have to be entered as a string but I'm not completely sure about that. The villages should be automatically added to the farm list, if you do not want the scout feature I think you can disable it in the attack manager script.

**Comment by Sn0x92** [comment]
I have already tried to enter the ids in an array string. Unfortunately without success.
In the troop manager I tried to activate "Can_Scout" even without success

**Comment by stefan2200** [comment]
Yes the bot automatically calculates the closest villages so player owned villages might get skipped, you can disable some BB's in the attacks cache files by setting safe to False.

It also features the possibility to automatically manage the farms based on the resources they produce per run, this could be done by running the manager.py script so your player owned villages should get farmed more often.

If you still cannot farm enough there is also the possibility to change line 81 in attack.py
`if village['owner'] != "0" and vid not in self.extra_farm:
     continue`
To 
`if village['owner'] == "0" or vid not in self.extra_farm:
    continue`
Which should completely disable BB farming :)

**Comment by Sn0x92** [comment]
I've seen every now and then he sends out spy attacks (think new BBs). But unfortunately the bot has attacked or spied zero players so far?

       "additional_farms": [1234, 12345, 12346, 123457],

So I set the config but unfortunately nothing happens there?

**Comment by stefan2200** [comment]
Try looking up the Village ID in the village cache folder, it should contain a safe parameter. Setting that to true will skip all checks for that village so then it will probably attack.
