### ISSUE TITLE
No module named 'core'

### ISSUE THREAD

**Issue by ghost** [stefan2200/TWB#108]
Tried to implement as a docker container with python 3.9.

Stucks at:

Traceback (most recent call last):
  File "/usr/src/app/./twb.py", line 35, in <module>
    from core.notification import Notification
ModuleNotFoundError: No module named 'core'

**Comment by stefan2200** [comment]
Are you invoking the script from the correct Python working directory? so the app one and not `python /usr/src/app/twb.py` ? 
It is likely an invalid environment setup but you might be able to hotfix it by adding this:
```
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
```
to the start of the twb.py file

**Comment by ghost** [comment]
Thx for the fast response. I doublechecked and found the error. Now its asking for the cookie string. What exactly is needed?
