### ISSUE TITLE
Webserver IP

### ISSUE THREAD

**Issue by Steby5** [stefan2200/TWB#116]
What do I need to change for webUI to be accessible from another device on same LAN? Currently web servers starts on 127.0.0.1 (localhost) but I want to use this webUI from my laptop (different device on the same network).

**Comment by suchencjusz** [comment]
Hello, you have to change in the file https://github.com/stefan2200/TWB/blob/09c8c872f37afb698c83e653f23a6c2668bdfb67/webmanager/server.py#L253C1-L253C44 from "localhost" to "0.0.0.0".

**Comment by Steby5** [comment]
thanks. i also needed to edit this line
https://github.com/stefan2200/TWB/blob/09c8c872f37afb698c83e653f23a6c2668bdfb67/webmanager/server.py#L255
with same code for it to work.
