### ISSUE TITLE
Support for more than one village ?

### ISSUE THREAD

**Issue by Sn0x92** [stefan2200/TWB#2]
Hey, i want to use more than one village how can i  setup this ? 
In my config i edit the file like this: 
https://pastebin.com/aW7Xsj9i

But it crash i tryt many options but nothing works

**Comment by stefan2200** [comment]
Hi, I noticed you added the "villages": parameter twice. This parameter is a dictionary so it should only be added once: [https://www.w3resource.com/JSON/structures.php](https://www.w3resource.com/JSON/structures.php)

It should be configured like this:
```
 "villages": {
    "your first village id": { village parameters },
    "your second village id": { village parameters }, 
    "your third village id etc...": { village parameters }
}
```
