### ISSUE TITLE
ready-made voids

### ISSUE THREAD

**Issue by wukapl** [stefan2200/TWB#30]
Cool bot. I would like to add to project a few voids parsing data from:
screen=overview_villages&mode=combined
screen=overview_villages&mode=prod
screen=overview_villages&mode=trader
screen=overview_villages&mode=commands
screen=overview_villages&mode=incomings

I have it written in c # if that's not a problem?

**Comment by stefan2200** [comment]
Closing because of premium account required to access these pages
