### ISSUE TITLE
Bot does not queue buildings/recruit troops...

### ISSUE THREAD

**Issue by insanem3rlin** [stefan2200/TWB#35]
Hi, 

I just started using your bot and I have to say that I am really impressed by your work!
I started a new world to test it out for the first time and the problem now is that it does not seem to do anything. The only console log I get is:
![log](https://user-images.githubusercontent.com/94021711/190974362-2d790b9d-a58b-4674-a698-29820edfddd0.png)
So in my understanding the only thing working is the FarmManager, which obviously doesn't do much at the start of a new world...
I also checked the configurations if something may be set to false, but as the picture shows,
![building](https://user-images.githubusercontent.com/94021711/190974863-ab58a8d0-cc71-48bc-b5c5-ff5506a1e431.png)
 e.g. the building manager is set to true (that is also the case in my config.py).

I guess there is just a small change to be done that would fix this...

Thanks in advance for the answer and above all for the tremendious work you did!

Greetings from Austria,

Konstantin

**Comment by insanem3rlin** [comment]
Ok, I guess the best solution, as always, was to restart it. Everything seems to be working now, maybe you could include it in the readMe that you have to restart the server after the first use to ensure that it recognizes your village, that seemed to be the case with me.
Nonetheless I want to thank you again for supplying us with this masterpiece!
I would love to treat you to a cup of coffee or sth else if you have paypal or venmo or sth similar :D

**Comment by stefan2200** [comment]
Always restart man!
But really nice that you like my bot :)

I'm aware of the automated village adding issue and it is actually caused by the bot not adding the villages until the next run. This is somehow failing in the initial setup but I have no idea how and where.
