### ISSUE TITLE
What does "Max_lookahead" mean?

### ISSUE THREAD

**Issue by MAHardo** [stefan2200/TWB#45]
Hi, 
I don't understand, what `Max_lookahead` actually means. When I have `Max_queued_items` at 5, what value should I use for `Max_lookahead`?

Thanks!

**Comment by MAHardo** [comment]
Alright, thanks a lot!

**Comment by stefan2200** [comment]
The `Building queue out of sync` message should only appear when you have manually queued buildings when the bot was active  (or at least what I expect). After the buildings finish it should resume its regular queue.

**Comment by MAHardo** [comment]
Okay, thanks mate!
