### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by Tomeo213** [stefan2200/TWB#6]
FileNotFoundError: [WinError 3] System could not find path '../cache\\reports'. This issue just popped in when I tried to run the server.py, and opened the "http://127.0.0.1:5000/" site.  I don't really know why. I also tried pasting the folder in diff locations to see if that would help, like python dictionary, the TWB main dictionary etc. Same thing happened when I tried to run the server from "webmanager". It gave me a screaming error, that there is no file called "webmanager" (lol), but I managed to fix this just by moving over the server.py to main dir.

Now I tried just removing the "reports" from the code overall, that just ended up giving me an error over "villages" in cache, that it could not find that file too. There seems to be a problem with finding the "cache" files, or I'm just retarded and can't see a easy solution

**Comment by stefan2200** [comment]
Hi, have you tried running the bot `twb.py` first? The bot itself runs in a separate script, the webmanager only allows the easy editing of config files. If that works please make sure you are running server.py from the webmanager directory. If it tells you there is no module named webmanager please make sure the script runs with Python version 3.6 of above.

Please let me know if you still having issues :)

**Comment by Tomeo213** [comment]
Yeah, I'm running the script for the bot just fine, "server.py" screams at me about the web module, even tho I have python 3.8.

**Comment by Tomeo213** [comment]
One second, I might have found the source of the problems

**Comment by Tomeo213** [comment]
Yeah, I found the reason. Some leftovers from python 3.5 were on my system, and the cmd was using a non existing version of it. Had to modify PATH, along with some registry files, thanks for the help!
