### ISSUE TITLE
Stuck in FarmManager

### ISSUE THREAD

**Issue by acok06** [stefan2200/TWB#75]
![image](https://github.com/stefan2200/TWB/assets/77898458/5fbe2e2c-4cb5-46d2-bfa5-2cac7c766326)

How can I fix this ?

**Comment by acok06** [comment]
> For me it was:
> 
> 1. Premium account
> 2. Farm assistant
> 3. Sync time on PC with the one on server

I have all of these :(

**Comment by acok06** [comment]
@stefan2200

**Comment by telmoenmartins** [comment]
You can try to add the village manually on the `config.json` file at the end on the 

`villages` object you can add it like this 


`"villages": {
    "your_village_id": {
      "building": "purple_predator",
      "units": "basic",
      "managed": true,
      "scout_first": false,
      "additional_farms": [],
      "prioritize_building": false,
      "prioritize_snob": false,
      "trade_for_premium": false,
      "gather_enabled": false,
      "gather_selection": 1,
      "advanced_gather": true,
      "snobs": 0,
      "evacuate_fragile_units_on_attack": false,
      "support_others": false,
      "support_others_factor": 0.25,
      "support_others_max_villages": 2,
      "request_support_on_attack": false
    }
  }`

you can edit all the options as you want and to get the village id in in the default url of the game `.tribalwars.com/game.php?village=id_here&screen=overview`

**Comment by pizzalord22** [comment]
@acok06 are you still experiencing the problem?

**Comment by stefan2200** [comment]
Fixed in GH-99
