### ISSUE TITLE
Use on different accounts on the same computer

### ISSUE THREAD

**Issue by SaamCosta** [stefan2200/TWB#81]
I forgot to ask about this, is there a way to use the bot on different accounts on the same computer? I'm thinking about testing this to help my sister max her account when she's not playing on her computer

**Comment by Scn64** [comment]
The only way I know of is to have two separate installations of the bot running in separate directories.

**Comment by stefan2200** [comment]
Correct, you can copy the bot folder and give it a new name. Removing the `config.json` file allows you to set it up with different accounts.
