### ISSUE TITLE
Can't launch the twb.py

### ISSUE THREAD

**Issue by GiambaJ1** [stefan2200/TWB#82]
I launch it by cmd but It lend me to some errrors like: Import error cannont import name 'PyQueryì from 'pyquery' (unknown location);
or either error in module from game.village import Village;
or either error in module from core.twstats import TwStats;
or either errror in module from pyquery import PyQuery as pq.

What should I do??

**Comment by stefan2200** [comment]
Running `python -m pip install --upgrade -r requirements.txt` should solve the issue.

**Comment by GiambaJ1** [comment]
> Running `python -m pip install --upgrade -r requirements.txt` should solve the issue.

I don't understand what you mean...

**Comment by GiambaJ1** [comment]
I've downloaded all the the file of requirements.txt and added into the bot folder.

**Comment by stefan2200** [comment]
I think you are trying to launch the bot from inside the Python interpreter. You should be able to execute the bot by opening cmd/powershell in the folder and entering `python twb.py`. You don't have to launch it from within Python.

**Comment by SleepingShadow-bit** [comment]
Thank you. ... But next Break
PS C:\Users\xxx\Downloads\TWB-master\TWB-master> python twb.py
Traceback (most recent call last):
  File "C:\Users\xxx\Downloads\TWB-master\TWB-master\twb.py", line 5, in <module>
    import coloredlogs
ModuleNotFoundError: No module named 'coloredlogs'
PS C:\Users\xxx\Downloads\TWB-master\TWB-master>

**Comment by stefan2200** [comment]
Included Windows installer script in 5fef851
